gravitee-io/gravitee-bom

- pom.xml
Use junit-bom to define version for all junit jupiter deps instead of adding them one by one
> Use junit-bom to define version for all junit jupiter deps

- README.adoc
- pom.xml
Bump patch version for the following dependencies: 
- logback
- slf4j
- spring
- spring security
- vertx
Aligned Jackson (move to 2.13) and Netty (minor patch) to the version defined in `vertx-dependencies` pom:
> Bump patch version of some dependencies

- .circleci/config.yml
- pom.xml
Usage of `mvn versions:use-releases` in projects using 2.3 or 2.4 version of BOM fails because there is no version declared in some dependency.
> fix: must add the version since it is in dependency management

- pom.xml
**Issue**
NA
Revert https://github.com/gravitee-io/gravitee-bom/pull/51 due to an issue with Vert.x update; a version 4.0.0 will be done instead.
> Revert "Bump Vertx, Jackson, Netty, Spring, Spring Security and AssertJ #51"

- pom.xml
**Issue**
NA
Versions for `jackson` and `netty` are the ones defined in `vertx-dependencies`
BREAKING CHANGE: Vert.x update might contain breaking changes.
Other dependencies will be updated in another PR
---
- use it directly by updating your project with version: `4.0.0-dep-major-update-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gravitee-bom/4.0.0-dep-major-update-SNAPSHOT/gravitee-bom-4.0.0-dep-major-update-SNAPSHOT.zip)
> Bump `vertx`, `jackson`, `netty` and a couple of other deps

- .circleci/config.yml
**Issue**
N/A
Bump gravitee-orb to allow alpha release
---
- use it directly by updating your project with version: `4.0.0-create-alpha-release-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gravitee-bom/4.0.0-create-alpha-release-SNAPSHOT/gravitee-bom-4.0.0-create-alpha-release-SNAPSHOT.zip)
> bump gravitee-orb

- pom.xml
**Issue**
https://github.com/gravitee-io/issues/issues/8257
- Bump mockito version to latest version 5.1.1
- Import mockito bom
- Declare mockito-core, mockito-inline, and mockito-junit-jupiter in dependencies managment
---
- use it directly by updating your project with version: `4.0.0-8257-update-mockito-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gravitee-bom/4.0.0-8257-update-mockito-SNAPSHOT/gravitee-bom-4.0.0-8257-update-mockito-SNAPSHOT.zip)
> bump mockito version to latest and use bom

- pom.xml
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-216
Upgrade to spring 6 and other dependencies:
- Spring 5.3.27 -> 6.0.9
- Spring Security 5.5.8 -> 6.1.0
- Jersey 2.35 -> 3.1.1
- Jetty 9.4.44.v20210927 -> 11.0.15
---
- use it directly by updating your project with version: `5.0.0-archi-216-spring6-run-e2e-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gravitee-bom/5.0.0-archi-216-spring6-run-e2e-SNAPSHOT/gravitee-bom-5.0.0-archi-216-spring6-run-e2e-SNAPSHOT.zip)
> feat: upgrade to spring6

- .circleci/config.yml
- .github/renovate.json
- pom.xml
**Issue**
N/A
- Bump dependencies, mainly Vert.x and Logback
- Remove RxJava2 dependency, as RxJava3 is expected to be used instead
- Use the latest gravitee-parent `22.0.0`
- Bump gravitee-orb to `4.1.0`
---
- use it directly by updating your project with version: `6.0.0-upgrade-vertx-and-deps-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gravitee-bom/6.0.0-upgrade-vertx-and-deps-SNAPSHOT/gravitee-bom-6.0.0-upgrade-vertx-and-deps-SNAPSHOT.zip)
> Major upgrade of Gravitee BOM

- pom.xml
**Issue**
N/A
Use the latest version of Jackson and Netty libraries
---
- use it directly by updating your project with version: `6.0.1-fix-bump-other-dependencies-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gravitee-bom/6.0.1-fix-bump-other-dependencies-SNAPSHOT/gravitee-bom-6.0.1-fix-bump-other-dependencies-SNAPSHOT.zip)
> fix: get the latest versions of jackson and netty

- pom.xml
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-296
See diff to understand changes
**Additional context**
---
- use it directly by updating your project with version: `7.0.0-archi-296-upgrade-bom-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gravitee-bom/7.0.0-archi-296-upgrade-bom-SNAPSHOT/gravitee-bom-7.0.0-archi-296-upgrade-bom-SNAPSHOT.zip)
> feat: upgrade bom to latest

- .github/renovate.json
Disable Renovate on 3.x to avoid automatic upgrade PRs that are irrelevant to this old version. 
Manual upgrades are possible if needed.
We encourage you to either use the latest 6.x or 7.x version.
> chore: disable renovate on 3.x branch

- .github/renovate.json
The gravitee-bom is still used by 3.20.x versions. This PR re-enables renovate but limits the upgrades to patch only
> chore: reactivate renovate on 3.x with patch upgrade only

- pom.xml
BREAKING CHANGE: upgrade vertx to 4.5.7
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-345
Upgrade Vert.x and Netty version, add bouncycastle in bom.
One BC in Vert.x upgrade need to be manage (https://github.com/vert-x3/wiki/wiki/4.5.4-Deprecations-and-breaking-changes#breaking-change-in-the-tls-configuration-of-tcp-client)
> feat: upgrade dependencies and add bouncycastle in bom

- pom.xml
**Issue**
Netty version was not overridden as it should
Add exoplicit deps instead
**Additional context**
---
- use it directly by updating your project with version: `8.2.10-fix-netty-version-override-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gravitee-bom/8.2.10-fix-netty-version-override-SNAPSHOT/gravitee-bom-8.2.10-fix-netty-version-override-SNAPSHOT.zip)
> fix: override netty deps by using direct deps into pom

- .github/renovate.json
- .github/renovate.json5
- Drop support for 6.x and 7.x version. Those versions are not used anymore. 
- 7.x is used by APIM 4.3 but EOL is coming when APIM 4.7 will be released (end of march). 
- AM does not use 7.x anymore
- Use the Gravitee preset.
- Use json5 extension to allow comments to explain rules
**Additional context**
> Renovate configuration improvments

- .github/renovate.json5
- pom.xml
This reverts upgrade of opentelemetry back to v1.39.
---
- use it directly by updating your project with version: `8.2.19-revert-opentelemetry-to-v1-39-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gravitee-bom/8.2.19-revert-opentelemetry-to-v1-39-SNAPSHOT/gravitee-bom-8.2.19-revert-opentelemetry-to-v1-39-SNAPSHOT.zip)
> Revert "fix(deps): update io.opentelemetry:opentelemetry-bom to v1.48.0"

- pom.xml
---
- use it directly by updating your project with version: `8.2.22-upgrade-spring-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gravitee-bom/8.2.22-upgrade-spring-SNAPSHOT/gravitee-bom-8.2.22-upgrade-spring-SNAPSHOT.zip)
> fix: update spring security to 6.4.4

- .github/renovate.json5
**Issue**
https://github.com/gravitee-io/issues/issues/XXXXX
It seems that the `enable` is not accepted anymore in Renovate. Here is the error message that we have :
> Source: .github/renovate.json5
> Reason: The renovate configuration file contains some invalid settings
> Message: Invalid configuration option: packageRules[3].enable
In the documentation, it seems that we need to use `enabled` (https://docs.renovatebot.com/configuration-options/#enabled)
---
- use it directly by updating your project with version: `8.3.0`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/ …
> chore: fix renovate configuration

- pom.xml
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-569
Upgrade Vertx to 4.5.18 and Netty 4.1.124.Final.
(No breaking change between 4.5.13 and 4.5.18)
---
- use it directly by updating your project with version: `8.3.30-archi-569-upgrade-vertx-4-5-18-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gravitee-bom/8.3.30-archi-569-upgrade-vertx-4-5-18-SNAPSHOT/gravitee-bom-8.3.30-archi-569-upgrade-vertx-4-5-18-SNAPSHOT.zip)
> fix(deps): upgrade vertx 4.5.18

- pom.xml
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-580
Upgrade Vertx to 4.5.21 and Netty 4.1.126.Final.
(No breaking change between 4.5.18 and 4.5.21)
---
- use it directly by updating your project with version: `8.3.38-fix-upgrade-vertx-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/gravitee-bom/8.3.38-fix-upgrade-vertx-SNAPSHOT/gravitee-bom-8.3.38-fix-upgrade-vertx-SNAPSHOT.zip)
> fix(deps): upgrade vertx 4.5.21
